### ISSUE TITLE
Don't vibrate if phone is in Silent Mode. + some suggestion

### ISSUE THREAD

**Issue by jsximes** [httpdispatch/MissedNotificationsReminder#12]
I made a small patch so the Reminder won't vibrate if the phone is in silent mode. It is attached in the link below.

Using code from http://stackoverflow.com/questions/2048427/how-can-i-detect-whether-the-android-phone-in-silent-mode-programatically
+   AudioManager manager = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);
+   return manager.getRingerMode() == AudioManager.RINGER_MODE_SILENT;

The app is great! I hope to see it soon definitely added to the android.

Also I would make a suggestion about customization of the scheduler. My Cyanogenmod android kit-kat already have a programmable scheduler (called Quiet Hours) to set to enter silent mode, vibration only, turn off the notification led, and many other behaviours on programmable times (however not by day-of-the-week). My guess is that such scheduler improvements should not be done in this app... so won't override the android features... I think rarely someone will need a different behaviour for each app/time/day/reminder notif./app notification/vibrate/led/sound....

Thanks!!!

[0001-Dont-vibrate-if-phone-is-is-Silent-Mode.patch.txt](https://github.com/httpdispatch/MissedNotificationsReminder/files/417686/0001-Dont-vibrate-if-phone-is-is-Silent-Mode.patch.txt)

**Comment by httpdispatch** [comment]
Thank You for the patch. I will try to apply it with some modifications in the nearest future. I think the app should stop schedule new reminders for the cases when ringer mode is changed to RINGER_MODE_SILENT until ringer mode is not changed back to some noisy one . This will allow to do not wake device periodically for no reason and reduce battery usage.

I agree regarding scheduler modification: that will be the very big update for such a small tool.

**Comment by httpdispatch** [comment]
Added. Thanks for your contribution
