### ISSUE TITLE
Off-topic: Suggested reminder Interval options: Minutes/Seconds

### ISSUE THREAD

**Issue by davidhedlund** [httpdispatch/MissedNotificationsReminder#13]
The shortest reminder Interval is currently 0.25 minutes (15 seconds). I would like to have it set to 1 second so I can use it as alarm clock with a short notification sound.

Alarm clocks do beep at least every 5 seconds but shorter reminder intervals may be required for some people that easily fall asleep.

**Comment by httpdispatch** [comment]
You may use minimum reminder interval of 5 seconds, which is 0.084 minutes, but you should enter value by hand in the edit text box (seekbar has minimum 0.25). I am not sure android alarm manager will work properly for such short intervals but you may try.

**Comment by davidhedlund** [comment]
@httpdispatch Thank you.

I suggest that you add a drop down menu with minutes/seconds as options.

**Comment by davidhedlund** [comment]
[mylabel:enhancement](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aenhancement%22+in%3Acomments&type=Issues&ref=searchresults)
