### ISSUE TITLE
Add a scheduler or widget to temporary turn off app.

### ISSUE THREAD

**Issue by httpdispatch** [httpdispatch/MissedNotificationsReminder#2]
@vanja-krk: it would be good to see some a)widget to temporary turn off app, or b)some kind of scheduler to turn app during night.

**Comment by vanja-krk** [comment]
fingers crossed!!

happy to help again!

**Comment by httpdispatch** [comment]
@vanja-krk can you please test this version of app. I've added custom scheduler there

https://drive.google.com/file/d/0B4hn2M3Klm4MazhRdjN5UkNNTTA/view?usp=sharing

**Comment by vanja-krk** [comment]
hello again! nice to hear you!
i downloaded this newest version, installed it over existent (it went all ok).
about scheduler - enabled/disabled is clear.
but, i'm little confused about "working period"/"disabled period". 
what did you mean with that? 
from my POW - one switch for enable/disable, and second field/pull down menu for "silent time".

so, how did you mean to set silent time? is silent time when is green line (working period) or "working perios" is only time when it will make sound?

huh, i complicated it now! :)

**Comment by httpdispatch** [comment]
You need to specify period for scheduler. Second switch is for setting of scheduler type. If you set "working time" then the reminder will work only within selected period from-to. Disabled period option inverses logic, so you specify period when reminder should not work. That may be confusing but i don't know the better ux of how to disable app for example from 2am to 7am. If you need to disable app at night use "working period" option

**Comment by httpdispatch** [comment]
Disabled period = silent time
Working period = not silent time

**Comment by vanja-krk** [comment]
as i tought. but, do you think that will be good to change "working period" to "loud time", and "disabled period" to "silent time"? imho, that will suggest what option is selected at first look.

**Comment by httpdispatch** [comment]
Not sure what is the best option there

**Comment by vanja-krk** [comment]
i wrote my opinion.
