### ISSUE TITLE
Reminders stop when notification bar is opened on Android 8.0

### ISSUE THREAD

**Issue by rryk** [httpdispatch/MissedNotificationsReminder#23]
Same happens when sliding a reminder down in the lock screen to reveal action buttons. This happens because app depends on AccessibilityService to detect cancelled notifications. On Android 8.0, while sliding the notifcations bar open, several TYPE_WINDOW_CONTENT_CHANGED accessibility events are generated and when the user open bar slowly enough, the root accessibility node does not contain list of notifications since they are not yet visible on the screen. The app then thinks they were all removed and stops reminding the user.

**Comment by rryk** [comment]
One solution to this would be use NotificationListenerService instead of AccessibilityService, but unfortunately that is only available starting from API version 18 (Android 4.3), whereas current version of the app supports devices from version 14 (Android 4.0). Depending solely on NotificationListenerService would mean making app not compatible with older devices, but not moving to it makes the experience suboptimal on newer devices.

It would be nice to support both mechanisms and choose them at runtime, but I am not sure whether this is possible.

**Comment by httpdispatch** [comment]
App has multiple versions (flavours): v14 and v18. V18 uses NotificationListenerService so that is not necessary to put any efforts to fix v14 compatibility with Android 8.

**Comment by httpdispatch** [comment]
@rryk see https://github.com/httpdispatch/MissedNotificationsReminder/blob/db0811e7407c453b2cc5d12f56b526757495c43e/app/src/v18/java/com/app/missednotificationsreminder/service/AbstractReminderNotificationListenerService.java

**Comment by rryk** [comment]
Oh! I see. Sorry for being a noob :-). Then I need to port my changes in the pull request #22 to this version as well. What other versions are there? Do you know how can I switch active version in Android Studio?

**Comment by rryk** [comment]
Updated #22. After some looking around, found build types and product flavors in the project settings.

**Comment by httpdispatch** [comment]
There is a "Build Variants" button in the bottom left corner of the "Android Studio". 
![](http://tulipemoutarde.be/images/2013/build-variants.png)

**Comment by httpdispatch** [comment]
You don't need to modify #22 such as it is compatible with both V14 and V18 variants

**Comment by rryk** [comment]
Thanks a lot. This can be closed as WontFix.
