### ISSUE TITLE
doesn't seem to work with notifications from Calendar Notifications

### ISSUE THREAD

**Issue by thoraxe** [httpdispatch/MissedNotificationsReminder#54]
I really like how https://github.com/quarck/CalendarNotificationNG batches calendar notifications and lets you mass-snooze and etc. I may give Calendar Snooze a try. 

Unfortunately Android 10 seems to have broken the way that Calendar Notification works with vibration when the phone is in vibrate mode. So I tried Missed Notifications Reminder.

Unfortunately, MNR will let me select Calendar Notification as an app, and MNR even shows that it sees an active notification from Calendar Notification. However, even with Calendar Notification selected to be reminded, it doesn't actually work / do anything. In other words, Missed Notifications Reminder is not actually acting on the notification from Calendar Notification.

I'll attach some screenshots and the device log.

**Comment by thoraxe** [comment]
![Screenshot_20200522-072203](https://user-images.githubusercontent.com/94413/82663098-09b35400-9bfd-11ea-947f-2e85bfbcdc6b.png)
![Uploading Screenshot_20200522-072152.png…]()

**Comment by thoraxe** [comment]
![Screenshot_20200522-072152](https://user-images.githubusercontent.com/94413/82663190-30718a80-9bfd-11ea-91f0-d3be7ead2c65.png)

**Comment by thoraxe** [comment]
https://gist.github.com/thoraxe/fd16e7bec94e28415a5b9abdc3a1a04d

**Comment by httpdispatch** [comment]
@thoraxe Looks like that app creates ongoing notification, which is by default ignored by the MNR app
"found ongoing match which is requested to be skipped"
You may disable that option in the MNR app advanced settings "Ignore ongoing notifications"

**Comment by thoraxe** [comment]
awesome, thanks!
