### ISSUE TITLE
Notification overlap

### ISSUE THREAD

**Issue by piccolbo** [httpdispatch/MissedNotificationsReminder#59]
Since some recent OS update (stock android on pixel 3) the reminder overlaps the main notification. The only way to read it is to dismiss the reminder. Swiping the reminder doesn't work anymore. May be related to #45.

**Comment by httpdispatch** [comment]
You may delay reminder notification creation in the app settings

**Comment by piccolbo** [comment]
I don't see the word "delay" in the settings, including advanced setting. Sorry probably just missing it. Can you tell me what section it is under? Also not sure what delay would do. I was thinking that the notification should appear one after the other, not overlapped, rather than overlap in a certain order.

**Comment by httpdispatch** [comment]
![image](https://user-images.githubusercontent.com/2315223/95163871-7cd6f480-07b1-11eb-841b-85032bde6422.png)
