### ISSUE TITLE
Unable to swipe away reminder notification

### ISSUE THREAD

**Issue by studgeek** [httpdispatch/MissedNotificationsReminder#62]
Starting a month or two ago I no longer seem able to to swipe away (left/right) the "Reminder is active" notification.  It only goes far enough to show the gear icon. I can still dismiss it by expanding it and clicking on "Dismiss".

I wonder if it may be Android version related. I am on a Pixel 3 XL on Android 11 with security updated 2020-10-05. Thx!

**Comment by httpdispatch** [comment]
That is because the app acts as a foreground service by default. If you prefer old behaviour just turn that option off.
