### ISSUE TITLE
Billing client

### ISSUE THREAD

**Issue by jugendhacker** [httpdispatch/MissedNotificationsReminder#68]
I'm currently trying to package the latest versions for F-Droid here https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8331. But it looks like you added com.android.billingclient with commit a51a1386e737f03956407fb99ae246418ebe8b9c, which is proprietary and thereby prevents inclusion of the newest versions in F-Droid.

**Comment by httpdispatch** [comment]
What is the best way to fix that? Separate branch without that library for f-droid? Or separate build flavor?

**Comment by jugendhacker** [comment]
Separate build flavor is usually the best solution, because then it's still mostly the same codebase and the maintenance effort isn't that big.

**Comment by httpdispatch** [comment]
https://github.com/httpdispatch/MissedNotificationsReminder/releases/tag/1.6.5.1

I've added separate flavor for no billing version. To build app use these commands
`gradlew :app:assembleAccessibilityV14NoProprietaryRelease`
`gradlew :app:assembleNotificationListenerV18NoProprietaryRelease`
