### ISSUE TITLE
Can't set times as needed

### ISSUE THREAD

**Issue by mperedithe** [httpdispatch/MissedNotificationsReminder#69]
Hello,  I really like this app.  I have two small issues.  1) The smallest amount of time that I can set the reminder for is 15 seconds and I need 3 seconds, and 2) the scheduler only allows for setting up a period within a day, I need to set it up to remind from 9pm to 5am.

For problem 1 I don't know if there's a Android level restriction.  I basically need the reminder act like a phone and ring every couple seconds until I answer.

For problem 2 maybe break away from the sliding bar?

I using this app so that I don't miss SMS alerts that are sent to me while I'm oncall.  SMS isn't ideal for emergencies, but it's the method my employer uses when alerts aren't picked up by the call center staff.  They escalate to the next person in line via SMS.

**Comment by httpdispatch** [comment]
1. You may set minimum amount to 0.08 which is 5 seconds
2. You may adjust working hour switch to non working hours. In that way you may specify non working period from 5am to 9pm
