### ISSUE TITLE
Not working Android 13

### ISSUE THREAD

**Issue by szanalmas** [httpdispatch/MissedNotificationsReminder#77]
The "Service access" cannot be enabled in Android 13. (For "security reasons" 13 does not allow...)

**Comment by httpdispatch** [comment]
It looks like Android 13 restricts any apps downloaded from third party sources. Here is an article mentioning that https://www.xda-developers.com/android-13-restricted-setting-notification-listener/. Also it mentions some workaround

**Comment by szanalmas** [comment]
Thank you!
